<?php

namespace EbicsApi\Ebics\Tests\Handlers;

use EbicsApi\Ebics\Contracts\HttpClientInterface;
use EbicsApi\Ebics\Contracts\SignatureInterface;
use EbicsApi\Ebics\Exceptions\SignatureEbicsException;
use EbicsApi\Ebics\Factories\Crypt\RSAFactory;
use EbicsApi\Ebics\Factories\EbicsFactoryV25;
use EbicsApi\Ebics\Factories\SegmentFactory;
use EbicsApi\Ebics\Factories\SignatureFactory;
use EbicsApi\Ebics\Handlers\AuthSignatureHandler;
use EbicsApi\Ebics\Handlers\ResponseHandler;
use EbicsApi\Ebics\Handlers\Traits\H004Trait;
use EbicsApi\Ebics\Handlers\Traits\H00XTrait;
use EbicsApi\Ebics\Models\Bank;
use EbicsApi\Ebics\Models\Crypt\Key;
use EbicsApi\Ebics\Models\Crypt\KeyPair;
use EbicsApi\Ebics\Models\Crypt\RSA;
use EbicsApi\Ebics\Models\EbicsClientOptions;
use EbicsApi\Ebics\Models\Http\Request;
use EbicsApi\Ebics\Models\Http\Response;
use EbicsApi\Ebics\Models\Keyring;
use EbicsApi\Ebics\Models\Order\StandardOrderResult;
use EbicsApi\Ebics\Models\User;
use EbicsApi\Ebics\Orders\HEV;
use EbicsApi\Ebics\Orders\HPB;
use EbicsApi\Ebics\Services\CryptService;
use EbicsApi\Ebics\Services\Processor\AESEncryptor;
use EbicsApi\Ebics\Services\Processor\Base64Encoder;
use EbicsApi\Ebics\Services\Processor\ZipCompressor;
use EbicsApi\Ebics\Services\RandomService;
use EbicsApi\Ebics\Services\TransactionKeyResolver;
use EbicsApi\Ebics\Tests\AbstractEbicsTestCase;
use EbicsApi\Ebics\EbicsClient;

/**
 * Test verification of the bank authentication signature (X002) of responses.
 *
 * @license http://www.opensource.org/licenses/mit-license.html  MIT License
 * @author Andrew Svirin
 *
 * @group bank-auth-signature
 */
class BankAuthSignatureVerificationTest extends AbstractEbicsTestCase
{
    use H00XTrait;
    use H004Trait;

    private ResponseHandler $responseHandler;
    private AuthSignatureHandler $authSignatureHandler;
    private CryptService $cryptService;
    private SignatureFactory $signatureFactory;
    private Keyring $keyring;

    /**
     * Keyring with the user signature X that plays the role of the bank key.
     * Its public and private parts are derived from the same fixture key,
     * so responses signed with it can be verified by the public key.
     */
    private Keyring $bankSigningKeyring;

    protected function setUp(): void
    {
        parent::setUp();

        $credentialsId = 2;
        $client = $this->setupClientV25($credentialsId);
        $this->setupKeys($client->getKeyring());
        $this->keyring = $client->getKeyring();

        $ebicsFactory = new EbicsFactoryV25();
        $aesEncryptor = new AESEncryptor(new TransactionKeyResolver());
        $rsaFactory = new RSAFactory($aesEncryptor);
        $this->cryptService = new CryptService(
            $rsaFactory,
            $aesEncryptor,
            new RandomService(),
            new Base64Encoder()
        );
        $this->signatureFactory = new SignatureFactory($rsaFactory);
        $this->responseHandler = $ebicsFactory->createResponseHandler(
            new SegmentFactory(),
            $this->cryptService,
            new ZipCompressor(),
            new Base64Encoder()
        );

        // Build the bank signing identity: a user signature X whose public
        // key is derived from the same private key used for signing.
        $keys = json_decode((string)file_get_contents($this->fixtures . '/keys.json'));
        $rsaPrivate = $rsaFactory->createPrivate(
            new Key($keys->X002, RSA::PRIVATE_FORMAT_PKCS1),
            'mysecret'
        );
        $publicKey = new Key(
            (string)$rsaPrivate->getPublicKey(RSA::PUBLIC_FORMAT_PKCS1),
            RSA::PUBLIC_FORMAT_PKCS1
        );
        $privateKey = new Key($keys->X002, RSA::PRIVATE_FORMAT_PKCS1);
        $bankSignatureX = $this->signatureFactory->createSignatureX($publicKey, $privateKey);

        $this->bankSigningKeyring = new Keyring(Keyring::VERSION_25);
        $this->bankSigningKeyring->setPassword('mysecret');
        $this->bankSigningKeyring->setUserSignatureX($bankSignatureX);

        // The verifying keyring holds the bank X002 public key of the signer.
        $this->keyring->setBankSignatureX($bankSignatureX);

        $this->authSignatureHandler = $ebicsFactory->createAuthSignatureHandler(
            new Base64Encoder(),
            $this->bankSigningKeyring,
            $this->cryptService
        );
    }

    /**
     * Load the SPR response fixture, replace its AuthSignature with one
     * generated by the passed auth signature handler and rewind the DOM.
     */
    private function createSignedResponse(AuthSignatureHandler $authSignatureHandler): Response
    {
        $xml = $this->createResponseFromFixture();
        $h00x = $this->getH00XVersion();
        $xpath = $this->prepareH00XXPath($xml);

        // Remove the AuthSignature from the fixture.
        $authSignature = $xpath->query('//' . $h00x . ':AuthSignature')->item(0);
        self::assertNotNull($authSignature);
        $authSignature->parentNode->removeChild($authSignature);

        $header = $xpath->query('//' . $h00x . ':header')->item(0);
        self::assertNotNull($header);
        $authSignatureHandler->handle($xml, $header);

        // Rewind. Because after remove and insert XML tree do not work correctly.
        $content = $xml->saveXML();
        self::assertIsString($content);
        $xml->loadXML($content);

        return $xml;
    }

    private function createResponseFromFixture(): Response
    {
        $xml = new Response();
        $content = file_get_contents($this->fixtures . '/spr.xml');
        self::assertIsString($content);
        $xml->loadXML($content);

        return $xml;
    }

    /**
     * Auth signature handler with a random "bank" identity that differs
     * from the trusted bank X002 key in the verifying keyring.
     */
    private function createForeignAuthSignatureHandler(): AuthSignatureHandler
    {
        $keyPair = $this->cryptService->generateKeyPair('testpassword');
        $signature = $this->signatureFactory->createSignatureXFromKeys(new KeyPair(
            $keyPair->getPublicKey(),
            $keyPair->getPrivateKey(),
            'testpassword'
        ));
        $foreignKeyring = new Keyring(Keyring::VERSION_25);
        $foreignKeyring->setPassword('testpassword');
        $foreignKeyring->setUserSignatureX($signature);

        return (new EbicsFactoryV25())->createAuthSignatureHandler(
            new Base64Encoder(),
            $foreignKeyring,
            $this->cryptService
        );
    }

    public function testVerifySuccess(): void
    {
        $response = $this->createSignedResponse($this->authSignatureHandler);

        $this->responseHandler->verifyAuthSignature($response, $this->keyring);

        // No exception means that the signature is valid.
        $this->addToAssertionCount(1);
    }

    public function testVerifyTamperedDataFails(): void
    {
        $response = $this->tamperResponse($this->createSignedResponse($this->authSignatureHandler));

        // Tamper with an authenticated node after signing.
        $h00x = $this->getH00XVersion();
        $xpath = $this->prepareH00XXPath($response);
        $returnCode = $xpath->query('//' . $h00x . ':body/' . $h00x . ':ReturnCode')->item(0);
        self::assertNotNull($returnCode);
        $returnCode->nodeValue = '099999';

        $this->expectException(SignatureEbicsException::class);
        $this->expectExceptionMessage('Digest value of the bank response does not match.');

        $this->responseHandler->verifyAuthSignature($response, $this->keyring);
    }

    public function testVerifyWrongBankKeyFails(): void
    {
        $response = $this->createSignedResponse($this->createForeignAuthSignatureHandler());

        $this->expectException(SignatureEbicsException::class);
        $this->expectExceptionMessage('Authentication signature of the bank response is invalid.');

        $this->responseHandler->verifyAuthSignature($response, $this->keyring);
    }

    public function testVerifyWithoutBankKeyFails(): void
    {
        $response = $this->createSignedResponse($this->authSignatureHandler);
        $this->keyring->setBankSignatureX(null);

        $this->expectException(SignatureEbicsException::class);
        $this->expectExceptionMessage('bank X002 key is not received yet');

        $this->responseHandler->verifyAuthSignature($response, $this->keyring);
    }

    public function testVerifyResponseWithoutAuthSignatureSkipped(): void
    {
        $xml = $this->createResponseFromFixture();
        $h00x = $this->getH00XVersion();
        $xpath = $this->prepareH00XXPath($xml);
        $authSignature = $xpath->query('//' . $h00x . ':AuthSignature')->item(0);
        self::assertNotNull($authSignature);
        $authSignature->parentNode->removeChild($authSignature);

        $this->responseHandler->verifyAuthSignature($xml, $this->keyring);

        // No exception means that the verification was skipped.
        $this->addToAssertionCount(1);
    }

    public function testVerifyMalformedAuthSignatureFails(): void
    {
        $response = $this->createSignedResponse($this->authSignatureHandler);

        // Remove the DigestValue node from the AuthSignature.
        $xpath = $this->prepareH00XXPath($response);
        $digestValue = $xpath->query('//' . $this->getH00XVersion() . ':AuthSignature/ds:SignedInfo/ds:Reference/ds:DigestValue')
            ->item(0);
        self::assertNotNull($digestValue);
        $digestValue->parentNode->removeChild($digestValue);

        $this->expectException(SignatureEbicsException::class);
        $this->expectExceptionMessage('Authentication signature of the bank response is malformed.');

        $this->responseHandler->verifyAuthSignature($response, $this->keyring);
    }

    public function testVerifyToleratesWhitespaceInDigestValue(): void
    {
        $response = $this->createSignedResponse($this->authSignatureHandler);

        // Simulate a bank that emits the digest value with formatting:
        // pad the digest value with whitespace allowed by xsd:base64Binary
        // and re-sign the modified SignedInfo, as the bank would have done.
        $h00x = $this->getH00XVersion();
        $xpath = $this->prepareH00XXPath($response);
        $digestValue = $xpath->query('//' . $h00x . ':AuthSignature/ds:SignedInfo/ds:Reference/ds:DigestValue')
            ->item(0);
        self::assertNotNull($digestValue);
        $digestValue->nodeValue = "\n  " . $digestValue->nodeValue . "\n";

        $signedInfo = $xpath->query('//' . $h00x . ':AuthSignature/ds:SignedInfo')->item(0);
        self::assertNotNull($signedInfo);
        $canonicalizedSignedInfo = trim((string)$signedInfo->C14N(false, false));
        $signature = $this->cryptService->encrypt(
            $this->bankSigningKeyring->getUserSignatureX()->getPrivateKey(),
            'mysecret',
            SignatureInterface::X_VERSION2,
            $this->cryptService->hash($canonicalizedSignedInfo)
        );
        $signatureValue = $xpath->query('//' . $h00x . ':AuthSignature/ds:SignatureValue')->item(0);
        self::assertNotNull($signatureValue);
        $signatureValue->nodeValue = base64_encode($signature);

        $this->responseHandler->verifyAuthSignature($response, $this->keyring);

        // No exception means that the whitespace was tolerated.
        $this->addToAssertionCount(1);
    }

    public function testClientSkipsVerificationForHpbOrder(): void
    {
        // The HPB response is signed with a key that differs from the bank key
        // stored in the keyring (simulating a bank key rotation). HPB delivers
        // new bank keys and must not be verified against the stored ones.
        $response = $this->createSignedResponse($this->createForeignAuthSignatureHandler());
        $client = $this->createClientWithFixedResponse($response);

        try {
            $client->executeInitializationOrder(new HPB());
            self::fail('Expected downstream processing failure after skipped verification.');
        } catch (SignatureEbicsException $exception) {
            self::fail('HPB response was verified against the stored bank keys instead of being exempted.');
        } catch (\Throwable $exception) {
            // Expected: verification was skipped and processing continued
            // into the order data extraction.
            self::addToAssertionCount(1);
        }
    }

    public function testClientVerifiesValidBankSignature(): void
    {
        $client = $this->createClientWithFixedResponse(
            $this->createSignedResponse($this->authSignatureHandler)
        );

        $result = $client->executeStandardOrder(new HEV());

        self::assertInstanceOf(StandardOrderResult::class, $result);
    }

    /**
     * Tamper with an authenticated node (ReportText) without changing the
     * return code, so that only signature verification can detect it.
     */
    private function tamperResponse(Response $response): Response
    {
        $h00x = $this->getH00XVersion();
        $xpath = $this->prepareH00XXPath($response);
        $reportText = $xpath->query('//' . $h00x . ':ReportText')->item(0);
        self::assertNotNull($reportText);
        $reportText->nodeValue = '[EBICS_TAMPERED] Tampered.';

        return $response;
    }

    public function testClientRejectsTamperedBankSignatureInStrictMode(): void
    {
        $response = $this->tamperResponse($this->createSignedResponse($this->authSignatureHandler));

        $client = $this->createClientWithFixedResponse($response);

        $this->expectException(SignatureEbicsException::class);

        $client->executeStandardOrder(new HEV());
    }

    public function testClientRejectsTamperedBankSignature(): void
    {
        // Verification is always strict: a tampered response must abort the
        // transaction with a SignatureEbicsException.
        $response = $this->tamperResponse($this->createSignedResponse($this->authSignatureHandler));

        $client = $this->createClientWithFixedResponse($response);

        $this->expectException(SignatureEbicsException::class);

        $client->executeStandardOrder(new HEV());
    }

    /**
     * Create an EBICS client that always responds with the fixed response.
     */
    private function createClientWithFixedResponse(Response $response): EbicsClient
    {
        $credentials = $this->credentialsDataProvider(2);

        $responseContent = $response->saveXML();
        self::assertIsString($responseContent);

        $httpClient = new class($responseContent) implements HttpClientInterface {
            public function __construct(private readonly string $content)
            {
            }

            public function post(string $url, Request $request): Response
            {
                $response = new Response();
                $response->loadXML($this->content);

                return $response;
            }
        };

        $options = new EbicsClientOptions();
        $options->setHttpClient($httpClient);
        $options->setSchemaDir($this->schema);

        $bank = new Bank($credentials['hostId'], $credentials['hostURL']);
        $user = new User($credentials['partnerId'], $credentials['userId']);

        return new EbicsClient($bank, $user, $this->keyring, $options);
    }
}
